[package]
name = "win-ftype"
version = "0.1.0"
edition = "2021"

[dependencies]

[target.'cfg(windows)'.dependencies]
normpath = "0.3.2"
windows = { version = "0.39.0", features = ["Win32_UI_Shell", "Win32_Foundation", "Win32_System_Memory"] }
